### ISSUE TITLE
Quit button access in controller

### ISSUE THREAD

**Issue by cebudding** [BCCN-Prog/2019_elegANT#15]
Hey everyone,

In the implemented full-screen mode of our game, a crucial component is the quit button(the normal option buttons wont be visible anymore). Since the controller receives the event of a click, we (View team) would like to request for implementing the same. P.S: We could implement this by calling the quit button via its ID (quit_button) using the function (get_element_by_id) and then implement the system quit option. This needs to be implemented both in the game view and in the start view.
Kindly DO NOT run the view without implementing this function as none of the other operating systems but Windows have an option to quit from the game.

**Comment by marcbue** [comment]
we implemented an event called: 'quit_game'.
If you give us this event when an appropriate button is pressed the controller will handle it.
You can close this ticket after you implemented the button in the view.
